name: besocial
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  firebase_messaging: ^6.0.16
  google_sign_in: ^4.5.1
  geolocator: ^5.3.2+2
  uuid: ^2.2.0
  image: ^2.1.12
  animator: ^2.0.1
  path_provider: ^1.6.11
  timeago: ^2.0.26
  cached_network_image:
  flutter_svg:
  flutter_auth_buttons: ^0.8.0
  flutter_facebook_login: ^3.0.0
  image_picker: ^0.6.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/



  fonts:
    - family: Signatra
      fonts:
        - asset: fonts/Signatra.ttf

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
    - family: Dancing_Script
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf

